services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: "unless-stopped"
    networks:
      - jellyfin
    ports: 
      - "8096:8096"
    devices:
      - /dev/dri:/dev/dri # hardware transcoding
    volumes:
      - $DOCKERDIR/appdata/jellyfin:/config
      - $DATADIR/media:/data/media
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID     