services:
  jellyseer:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: "unless-stopped"
    networks:
    - swag
    ports:
      - "5055:5055"
    volumes:
      - $DOCKERDIR/appdata/jellyseer:/app/config
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - "swag=enable"
      - "com.centurylinklabs.watchtower.enable=true"