services:
  jellyseer:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: "unless-stopped"
    networks:
     - jellyfin
     - arrs
    #ports:
    #  - "5055:5055"
    volumes:
      - $DOCKERDIR/appdata/jellyseer:/app/config
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - swag=enable