services:
  nzbhydra:
    image: lscr.io/linuxserver/nzbhydra2:latest
    container_name: nzbhydra2
    restart: "unless-stopped"
    networks:
      - swag
    #ports:
    #  - "5076:5076"
    volumes:
      - $DOCKERDIR/appdata/nzbhydra:/config
      - $DATADIR/usenet
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - "swag=enable"
      - "com.centurylinklabs.watchtower.enable=true"