services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest 
    container_name: radarr
    restart: "unless-stopped"
    networks:
      - swag
    #ports:
    #  - "7878:7878"
    volumes:
      - $DOCKERDIR/appdata/radarr:/config
      - $DATADIR:/data
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - "swag=enable"
      - "com.centurylinklabs.watchtower.enable=true"