services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    restart: "unless-stopped"
    networks:
      - nzbhydra
      - arrs
    ports:
      - "8787:8787"
    volumes:
      - $DOCKERDIR/appdata/readarr:/config
      - $DATADIR:/data
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID      