services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: "unless-stopped"
    networks:
      - swag
    ports:
      - "8086:8080" # this is probably already mapped to something else
    volumes:
      - $DOCKERDIR/appdata/sabnzbd:/config
      - $DATADIR/usenet:/data/usenet
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - "swag=enable"
      - "com.centurylinklabs.watchtower.enable=true"