services:
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    ports:
      - 81:81
      - 443:443
        #  - 80:80
    networks: 
      - swag
    # dockerproxy:
    cap_add:
      - NET_ADMIN
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      URL: $URL
      SUBDOMAINS: wildcard
      VALIDATION: dns
      DNSPLUGIN: cloudflare
      EMAIL: $EMAIL
      DOCKER_MODS: linuxserver/mods:swag-auto-proxy|linuxserver/mods:swag-cloudflare-real-ip|linuxserver/mods:universal-docker|linuxserver/mods:swag-dashboard
      #DOCKER_HOST: dockerproxy
    extra_hosts:
      - $URL:127.0.0.1
    volumes:
      - $DOCKERDIR/appdata/swag:/config
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
  authelia:
    image: ghcr.io/authelia/authelia:latest
    container_name: authelia
    user: "1000:1000"
    environment:
      - TZ: $TZ
    volumes:
      - $DOCKERDIR/appdata/authelia:/config
    restart: unless-stopped
