services:
  whisparr:
    image: ghcr.io/hotio/whisparr
    container_name: whisparr
    restart: "unless-stopped"
    networks:
      - swag
    #ports:
    #  - "6969:6969"
    volumes:
      - $DOCKERDIR/appdata/whisparr:/config
      - $DATADIR:/data
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - "swag=enable"
      - "com.centurylinklabs.watchtower.enable=true"