services:
  whisparr:
    image: ghcr.io/hotio/whisparr
    container_name: whisparr
    restart: "unless-stopped"
    networks:
      - nzbhydra
      - arrs
    ports:
      - "6969:6969"
    volumes:
      - $DOCKERDIR/appdata/whisparr:/config
      - $DATADIR:/data
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID