name: media-stack

#### Networks
networks:
  dockerproxy:
  swag:
    driver: bridge
include:
#### Core
  - yml/swag.yml
  - yml/dockerproxy.yml
#### Arrs
  - yml/radarr.yml
  - yml/sonarr.yml
  - yml/nzbhydra.yml
  #- yml/readarr.yml
  #- yml/lidarr.yml
  - yml/bazarr.yml
  # - yml/whisparr.yml 
#### Jellyfin
  - yml/jellyfin.yml
  - yml/jellyseer.yml
  - yml/jellystat.yml
#### Downloaders
  - yml/sabnzbd.yml
#### Utilities
  - yml/watchtower.yml
