name: media-stack

#### Networks
networks:
  nzbhydra:
  arrs:
  jellyfin:
include:
#### Core
  - yml/swag.yml
  - yml/dockerproxy.yml
#### Arrs
  - yml/radarr.yml
  - yml/sonarr.yml
  - yml/nzbhydra.yml
  - yml/readarr.yml
  - yml/lidarr.yml
  - yml/bazarr.yml
  # - yml/whisparr.yml ## commented out because I personally don't use it
#### Jellyfin
  - yml/jellyfin.yml
  - yml/jellyseer.yml
#### Downloaders
  - yml/sabnzbd.yml
#### Utilities
  - yml/watchtower.yml
